- eureka-common/src/main/java/edu/emory/cci/aiw/cvrg/eureka/common/comm/clients/ServicesClient.java
- eureka-services/src/main/java/edu/emory/cci/aiw/cvrg/eureka/services/resource/AuthenticationMethodResource.java
- eureka-services/src/main/java/edu/emory/cci/aiw/cvrg/eureka/services/resource/RoleResource.java
- eureka-services/src/test/java/edu/emory/cci/aiw/cvrg/eureka/services/resource/RoleResourceTest.java
-/api/protected/authenticationmethod to /api/protected/authenticationmethods
-/api/protected/role to /api/protected/roles
> Change URLs

- eureka-common/src/main/java/edu/emory/cci/aiw/cvrg/eureka/common/comm/clients/ServicesClient.java
- eureka-services/src/main/java/edu/emory/cci/aiw/cvrg/eureka/services/resource/AuthenticationMethodResource.java
- eureka-services/src/main/java/edu/emory/cci/aiw/cvrg/eureka/services/resource/FrequencyTypeResource.java
- eureka-services/src/main/java/edu/emory/cci/aiw/cvrg/eureka/services/resource/OAuthProviderResource.java
- eureka-services/src/main/java/edu/emory/cci/aiw/cvrg/eureka/services/resource/RelationOperatorResource.java
- eureka-services/src/main/java/edu/emory/cci/aiw/cvrg/eureka/services/resource/TimeUnitResource.java
- eureka-services/src/main/java/edu/emory/cci/aiw/cvrg/eureka/services/resource/ValueComparatorResource.java
- eureka-webapp/src/main/java/edu/emory/cci/aiw/cvrg/eureka/servlet/proposition/EditPropositionServlet.java
-1. AuthenticationMethod
-2. FrequencyType
-3. OAuthProvider
-4. RelationOperator
-5. TimeUnit
-6. ValueComparator
-Did NOT change role in master branch, because it is already correct
> Change URLs for master

- eureka-common/src/main/java/edu/emory/cci/aiw/cvrg/eureka/common/comm/clients/ServicesClient.java
- eureka-protempa-etl/src/main/java/edu/emory/cci/aiw/cvrg/eureka/etl/resource/DestinationResource.java
- eureka-protempa-etl/src/main/java/edu/emory/cci/aiw/cvrg/eureka/etl/resource/Destinations.java
- eureka-protempa-etl/src/main/java/edu/emory/cci/aiw/cvrg/eureka/etl/resource/JobResource.java
- eureka-services/src/main/java/edu/emory/cci/aiw/cvrg/eureka/services/config/EtlClient.java
- eureka-services/src/main/java/edu/emory/cci/aiw/cvrg/eureka/services/config/EtlClientImpl.java
- eureka-services/src/main/java/edu/emory/cci/aiw/cvrg/eureka/services/resource/DestinationResource.java
- eureka-services/src/main/java/edu/emory/cci/aiw/cvrg/eureka/services/resource/JobResource.java
- eureka-services/src/test/java/edu/emory/cci/aiw/cvrg/eureka/services/config/MockEtlClient.java
- eureka-webapp/pom.xml
- eureka-webapp/src/main/webapp/assets/css/eureka.css
- eureka-webapp/src/main/webapp/assets/js/eureka.cohort.js
- eureka-webapp/src/main/webapp/assets/js/eureka.editor.js
- eureka-webapp/src/main/webapp/eureka/module.js
- eureka-webapp/src/main/webapp/eureka/views/main/main.html
- eureka-webapp/src/main/webapp/index.html
- eureka-webapp/src/main/webapp/protected/categorization.jsp
- eureka-webapp/src/main/webapp/protected/cohort_editor.jsp
- eureka-webapp/src/main/webapp/protected/cohort_home.jsp
- eureka-webapp/src/main/webapp/protected/frequency.jsp
- eureka-webapp/src/main/webapp/templates/eureka_main.jsp
- repoint the menu items to the original working servlets and jsp pages
including Cohorts, Phenotypes, Jobs
- load News and Funding messages at the homepage
- fix banner flicker issue at loading
- fix load tree folders for Cohort Editor page
- fix drag and drop issue for Cohort Editor page
> Changes at front-end

- eureka-common/src/main/java/edu/emory/cci/aiw/cvrg/eureka/common/comm/AppProperties.java
- eureka-common/src/main/java/edu/emory/cci/aiw/cvrg/eureka/common/comm/AppPropertiesModes.java
- eureka-common/src/main/resources/application.properties
- eureka-services/src/main/java/edu/emory/cci/aiw/cvrg/eureka/services/config/ServiceProperties.java
- eureka-services/src/main/java/edu/emory/cci/aiw/cvrg/eureka/services/resource/AppPropertyResource.java
- eureka-webapp/src/main/webapp/eureka/config/app-properties.js
- eureka-webapp/src/main/webapp/eureka/help/views/main/main.html
- eureka-webapp/src/main/webapp/eureka/module.js
- eureka-webapp/src/main/webapp/eureka/views/main/main.html
- eureka-webapp/src/main/webapp/index.html
The code for fixing #48 has not yet implemented a bean with three fields for links, modes and registration, but uses a Map structure.
So the RESTful call (proxy-resource/appproperties) gets a Map instance. 
The code for enhancement#49 does have an AppProperties implemented, and I removed the Map structure there .
So now the RESTful call (proxy-resource/appproperties) gets an AppProperties instance.
> Fix bug #47, and #48, Implement enhancement #49

- eureka-protempa-etl/pom.xml
- eureka-protempa-etl/src/main/resources/dbmigration/changelog-master.xml
- eureka-services/pom.xml
- eureka-services/src/main/resources/dbmigration/changelog-master.xml
- pom.xml
removed the profiles in the pom.xml to avoid confusion and since i think it is never being used. Please review. i have tested it using embedded tomcat.
> make the superuser configurable in the pom.xml

- eureka-webapp/src/main/webapp/eureka/views/main/main.html
- eureka-webapp/src/main/webapp/index.html
> Implement spinner at menu bar and upper left box

- eureka-common/src/main/java/edu/emory/cci/aiw/cvrg/eureka/common/comm/Sequence.java
- eureka-common/src/main/java/edu/emory/cci/aiw/cvrg/eureka/common/entity/ExtendedPhenotype.java
- eureka-common/src/main/java/edu/emory/cci/aiw/cvrg/eureka/common/entity/Relation.java
- eureka-common/src/main/java/edu/emory/cci/aiw/cvrg/eureka/common/entity/SequenceEntity.java
- eureka-services/src/main/resources/Messages.properties
- eureka-services/src/main/resources/dbmigration/changelog-master.xml
- eureka-webapp/src/main/resources/Messages.properties
- eureka-webapp/src/main/webapp/protected/sequence.jsp
In order to solve the problem, I made several changes:
1. changelog-master.xml
Add extra column called SEQUENCES_ID in table EXTENDED_PHENOTYPES
Add a foreign key called FK_EXTENDED_PHENOTYPES_TO_SEQUENCES
**EXTENDED_PHENOTYPES**(SEQUENCES_ID)-----(many)----------(one)----->**SEQUENCES**(ID)
2. Change SequenceEntity.java, Relation.java, and ExtendedPhenotype.java accordingly
The change in sequence.jsp does not have direct relation for solving this problem, I just clean the code in the front-end, prevent strange behavior(s)
> Modify schema to solve #77 Can't delete sequence phenotype

- eureka-webapp/src/main/java/edu/emory/cci/aiw/cvrg/eureka/servlet/LoginServlet.java
- eureka-webapp/src/main/webapp/WEB-INF/web.xml
- eureka-webapp/src/main/webapp/gulpfile.js
- eureka-webapp/src/main/webapp/index.html
- eureka-webapp/src/main/webapp/karma.conf.js
- eureka-webapp/src/main/webapp/package.json
Add hash code at 
bulid/app-{hash code}.js
> Fix bug#83, Browser caching issues by adding hash to build/app.js

- eureka-services/src/main/java/edu/emory/cci/aiw/cvrg/eureka/services/resource/UserResource.java
- eureka-services/src/main/resources/dbmigration/changelog-master.xml
- eureka-services/src/test/java/edu/emory/cci/aiw/cvrg/eureka/services/dao/PropositionDaoTest.java
- eureka-services/src/test/java/edu/emory/cci/aiw/cvrg/eureka/services/dao/UserDaoTest.java
- eureka-services/src/test/java/edu/emory/cci/aiw/cvrg/eureka/services/resource/RoleResourceTest.java
- eureka-services/src/test/java/edu/emory/cci/aiw/cvrg/eureka/services/resource/UserResourceTest.java
- eureka-services/src/test/java/edu/emory/cci/aiw/cvrg/eureka/services/test/Setup.java
- eureka-webapp/src/main/java/edu/emory/cci/aiw/cvrg/eureka/servlet/worker/admin/EditUserWorker.java
- eureka-webapp/src/main/webapp/eureka/account/views/administration/edit/edit-controller.js
- eureka-webapp/src/main/webapp/eureka/account/views/administration/edit/edit.html
- eureka-webapp/src/main/webapp/protected/edit_user.jsp
Please review, thanks
1. Change changelog-master.xml to remove superuser role in the table
2. Modify validateUpdatedUser method in UserResource RESTful call
3. Modify some junit tests
4. Modify servlet file -- EditUserWorker
5. Change some front-end files
> Fix bug#64 Eliminate superuser role and account

- eureka-services/src/main/java/edu/emory/cci/aiw/cvrg/eureka/services/resource/UserResource.java
Logic is not valid in the previous validateUpdatedUser method.
> Fix validateUpdatedUser method

- eureka-webapp/src/main/webapp/eureka/cohorts/views/main/main.html
- eureka-webapp/src/main/webapp/eureka/directives/table-directive-two/table-directive-two.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/main/main-controller.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/main/main.html
Added ng-table to phenotypes after doing data load testing.  Cleaned up cohorts table after doing data load testing.   Fixed bug in directive-two.js
> Added ng-table to phenotypes

- eureka-webapp/src/main/webapp/eureka/eureka.less
- eureka-webapp/src/main/webapp/eureka/phenotypes/services/phenotype-service.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/main/main-controller.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/main/main.html
Was waiting to check in this batch of changes until last week changes were merged.
Center table in data for all tables
delete added to phenotypes.  *service is not working as expected will send email
> Center Data in table and delete added in phenotypes

- eureka-webapp/src/main/webapp/eureka/phenotypes/services/phenotype-service.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/main/main-controller.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/main/main.html
Able to delete phenotype from table after correcting api call
> Corrected phenotype delete call

- eureka-webapp/src/main/webapp/eureka/cohorts/views/edit/edit.html
- eureka-webapp/src/main/webapp/eureka/cohorts/views/main/main-controller.js
- eureka-webapp/src/main/webapp/eureka/cohorts/views/main/main.html
- eureka-webapp/src/main/webapp/eureka/cohorts/views/new/new.html
- eureka-webapp/src/main/webapp/eureka/phenotypes/services/phenotype-service.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/create/create-controller.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/create/create.html
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/edit/edit-controller.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/edit/edit.html
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/main/main-controller.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/main/main.html
Fix bug relating to delete.  Server side errors will be displayed in modal if delete fails
> Fix bug relating to delete

- eureka-webapp/src/main/webapp/eureka/config/app-properties.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/services/phenotype-service.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/create/create-controller.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/create/create.html
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/edit/edit.html
Working on tree component.
Able to navigate between nodes and
bread crumbs are working.
Still more tasks to do.
Also added in layout for phenotypes sections.
> Working on tree component and layout of phenotypes sections

- eureka-webapp/src/main/webapp/eureka/phenotypes/services/phenotype-service.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/create/create-controller.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/create/create.html
- eureka-webapp/src/main/webapp/eureka/services/drag-and-drop-service.js
- eureka-webapp/src/main/webapp/eureka/services/tree-service.js
Tree component updates
-Using correct rest services
-Able to add item to drop zone
-Checking for duplicates when adding to drop zone
-Delete items from drop zone
Still more to do
> Tree component updates

- eureka-webapp/src/main/webapp/eureka/cohorts/views/edit/edit-controller.js
- eureka-webapp/src/main/webapp/eureka/cohorts/views/edit/edit.html
- eureka-webapp/src/main/webapp/eureka/cohorts/views/new/new-controller.js
- eureka-webapp/src/main/webapp/eureka/cohorts/views/new/new.html
- eureka-webapp/src/main/webapp/eureka/directives/tree-component/tree-component-ctrl.js
- eureka-webapp/src/main/webapp/eureka/directives/tree-component/tree-component.html
- eureka-webapp/src/main/webapp/eureka/directives/tree-component/tree-component.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/create/create-controller.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/create/create.html
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/edit/edit-controller.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/edit/edit.html
Tree component directive has been added, along with other clean up items
> Added in tree component directive.

- eureka-webapp/src/main/webapp/eureka/cohorts/services/cohort-service.js
- eureka-webapp/src/main/webapp/eureka/cohorts/views/edit/edit-controller.js
- eureka-webapp/src/main/webapp/eureka/cohorts/views/edit/edit.html
- eureka-webapp/src/main/webapp/eureka/directives/tree-component/tree-component-ctrl.js
- eureka-webapp/src/main/webapp/eureka/directives/tree-component/tree-component.html
- eureka-webapp/src/main/webapp/eureka/services/drag-and-drop-service.js
Edit cohort is now working and tree component updated.  After testing will cleanup code for reuse.
> Edit Cohort is now working along with tree component changes

- eureka-webapp/src/main/webapp/eureka/cohorts/services/cohort-service.js
- eureka-webapp/src/main/webapp/eureka/cohorts/views/edit/edit-controller.js
- eureka-webapp/src/main/webapp/eureka/directives/tree-component/tree-component-ctrl.js
- eureka-webapp/src/main/webapp/eureka/services/drag-and-drop-service.js
Updating a Cohort should be working
> Updating a Cohort should be working

- eureka-webapp/src/main/webapp/eureka/cohorts/views/edit/edit-controller.js
- eureka-webapp/src/main/webapp/eureka/directives/tree-component/tree-component-ctrl.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/services/phenotype-service.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/create/create-controller.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/create/create.html
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/edit/edit-controller.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/edit/edit.html
- eureka-webapp/src/main/webapp/eureka/services/drag-and-drop-service.js
Changes to tree component and Phenotypes Categorization Create/Edit working.
In the middle of Frequency
> Changes to tree component and Phenotypes Categorization Create/Edit working.

- eureka-webapp/src/main/webapp/eureka/phenotypes/module.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/services/phenotype-service.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/create/create-controller.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/create/create.html
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/edit/edit-controller.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/edit/edit.html
Working on Sequence and Frequency views
> Phenotypes Update

- eureka-webapp/src/main/webapp/eureka/phenotypes/views/edit/categorization.html
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/edit/edit-controller.js
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/edit/edit.html
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/edit/frequency.html
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/edit/sequence.html
- eureka-webapp/src/main/webapp/eureka/phenotypes/views/edit/threshold.html
Added new folder structure for Phenotype Edit.  New structure will make it easy to fill in needed functionality.  Edit views are displaying.
> New folder structure for Phenotype Edit

- eureka-webapp/src/main/webapp/eureka/directives/tree-component/tree-component-ctrl.js
> Cleanup of tree component

- eureka-protempa-etl/src/main/resources/logging.properties
- eureka-services/src/main/resources/logging.properties
- eureka-services/src/test/resources/logging.properties
- eureka-webapp/src/main/resources/logging.properties
- src/main/resources/tomcat-eureka-config/logging.properties
> Updated Log levels
